const weatherIcons = {
  day: {
    "Sunny": "src/assets/day_svg/wi-day-sunny.svg",
    "Mostly Sunny": "src/assets/day_svg/wi-day-sunny.svg",
    "Partly Sunny": "src/assets/day_svg/wi-day-sunny.svg",
    "Intermittent Clouds": "src/assets/day_svg/wi-day-sunny-overcast.svg",
    "Hazy Sunshine": "src/assets/day_svg/wi-day-haze.svg",
    "Mostly Cloudy": "src/assets/day_svg/wi-day-cloudy.svg",
    "Cloudy": "src/assets/day_svg/wi-day-cloudy.svg",
    "Dreary": "src/assets/day_svg/wi-cloudy.svg",
    "Fog": "src/assets/day_svg/wi-day-fog.svg",
    "Showers": "src/assets/day_svg/wi-day-hail.svg",
    "Mostly Cloudy w/ Showers": "src/assets/day_svg/wi-day-hail.svg",
    "Partly Sunny w/ Showers": "src/assets/day_svg/wi-day-hail.svg",
    "T-Storms": "src/assets/day_svg/wi-day-thunderstorm.svg",
    "Mostly Cloudy w/ T-Storms": "src/assets/day_svg/wi-day-thunderstorm.svg",
    "Partly Sunny w/ T-Storms": "src/assets/day_svg/wi-day-thunderstorm.svg",
    "Rain": "src/assets/day_svg/wi-day-rain.svg",
    "Flurries": "src/assets/day_svg/wi-day-flurries.svg",
    "Mostly Cloudy w/ Flurries": "src/assets/day_svg/wi-day-flurries.svg",
    "Partly Sunny w/ Flurries": "src/assets/day_svg/wi-day-flurries.svg",
    "Snow": "src/assets/day_svg/wi-day-snow.svg",
    "Mostly Cloudy w/ Snow": "src/assets/day_svg/wi-day-snow.svg",
    "Ice": "src/assets/day_svg/wi-day-snow.svg",
    "Sleet": "src/assets/day_svg/wi-day-sprinkle.svg",
    "Freezing Rain": "src/assets/day_svg/wi-day-sleet-storm.svg",
    "Rain and Snow": "src/assets/day_svg/wi-day-sleet-storm.svg",
    "Windy": "src/assets/day_svg/wi-day-windy.svg",
  },
  night:{
    "Clear": "src/assets/night _svg/wi-night-clear.svg",
    "Mostly Clear": "src/assets/night _svg/wi-night-clear.svg",
    "Partly Cloudy": "src/assets/night _svg/wi-night-clear.svg",
    "Intermittent Clouds": "src/assets/night _svg/wi-night-alt-partly-cloudy.svg",
    "Hazy Moonlight": "src/assets/night _svg/wi-night-cloudy-windy.svg",
    "Mostly Cloudy": "src/assets/night _svg/wi-night-alt-cloudy.svg",
    "Cloudy": "src/assets/night _svg/wi-night-alt-cloudy.svg",
    "Dreary": "src/assets/night _svg/wi-cloudy.svg",
    "Fog": "src/assets/night _svg/wi-night-fog.svg",
    "Showers": "src/assets/night _svg/wi-night-alt-hail.svg",
    "Partly Cloudy w/ Showers": "src/assets/night _svg/wi-night-alt-hail.svg",
    "Mostly Cloudy w/ Showers": "src/assets/night _svg/wi-night-alt-hail.svg",
    "T-Storms": "src/assets/night _svg/wi-night-alt-thunderstorm.svg",
    "Partly Cloudy w/ T-Storms": "src/assets/night _svg/wi-night-alt-thunderstorm.svg",
    "Mostly Cloudy w/ T-Storms": "src/assets/night _svg/wi-night-alt-thunderstorm.svg",
    "Rain": "src/assets/night _svg/wi-night-alt-rain.svg",
    "Flurries": "src/assets/night _svg/wi-night-alt-flurries.svg",
    "Partly Cloudy w/ Flurries": "src/assets/night _svg/wi-night-alt-flurries.svg",
    "Mostly Cloudy w/ Flurries": "src/assets/night _svg/wi-night-alt-flurries.svg",
    "Snow": "src/assets/night _svg/wi-night-alt-snow.svg",
    "Mostly Cloudy w/ Snow": "src/assets/night _svg/wi-night-alt-snow.svg",
    "Ice": "src/assets/night _svg/wi-night-alt-snow.svg",
    "Sleet": "src/assets/night _svg/wi-night-alt-sprinkle.svg",
    "Freezing Rain": "src/assets/night _svg/wi-night-alt-snow-thunderstorm.svg",
    "Rain and Snow": "src/assets/night _svg/wi-night-alt-snow-thunderstorm.svg",
    "Windy": "src/assets/day_svg/wi-day-windy.svg",
  },
};

export default weatherIcons;