const weatherIcons = {
  day: {
    "Ensolarado": "src/assets/day_svg/wi-day-sunny.svg",
    "Predominantemente ensolarado": "src/assets/day_svg/wi-day-sunny.svg",
    "Parcialmente ensolarado": "src/assets/day_svg/wi-day-sunny.svg",
    "Nuvens intermitentes": "src/assets/day_svg/wi-day-sunny-overcast.svg",
    "Sol com névoa": "src/assets/day_svg/wi-day-haze.svg",
    "Predominantemente nublado": "src/assets/day_svg/wi-day-cloudy.svg",
    "Nublado": "src/assets/day_svg/wi-day-cloudy.svg",
    "Encoberto": "src/assets/day_svg/wi-cloudy.svg",
    "Névoa": "src/assets/day_svg/wi-day-fog.svg",
    "Chuveiros": "src/assets/day_svg/wi-day-hail.svg",
    "Predominantemente nublado com chuveiros": "src/assets/day_svg/wi-day-hail.svg",
    "Parcialmente ensolarado com chuveiros": "src/assets/day_svg/wi-day-hail.svg",
    "Trovoadas": "src/assets/day_svg/wi-day-thunderstorm.svg",
    "Predominantemente nublado com trovoadas": "src/assets/day_svg/wi-day-thunderstorm.svg",
    "Parcialmente ensolarado com trovoadas": "src/assets/day_svg/wi-day-thunderstorm.svg",
    "Chuva": "src/assets/day_svg/wi-day-rain.svg",
    "Flocos de neve": "src/assets/day_svg/wi-day-flurries.svg",
    "Predominantemente nublado com flocos de neve": "src/assets/day_svg/wi-day-flurries.svg",
    "Parcialmente ensolarado com flocos de neve": "src/assets/day_svg/wi-day-flurries.svg",
    "Neve": "src/assets/day_svg/wi-day-snow.svg",
    "Predominantemente nublado com neve": "src/assets/day_svg/wi-day-snow.svg",
    "Gelo": "src/assets/day_svg/wi-day-snow.svg",
    "Granizo": "src/assets/day_svg/wi-day-sprinkle.svg",
    "Chuva congelante": "src/assets/day_svg/wi-day-sleet-storm.svg",
    "Chuva e neve": "src/assets/day_svg/wi-day-sleet-storm.svg",
    "Ventoso": "src/assets/day_svg/wi-day-windy.svg",
    "Ensolarado com vento": "src/assets/day_svg/wi-day-sunny.svg",
    "Predominantemente ensolarado com vento": "src/assets/day_svg/wi-day-sunny.svg",
    "Parcialmente ensolarado com vento": "src/assets/day_svg/wi-day-sunny.svg",
    "Predominantemente nublado com vento": "src/assets/day_svg/wi-day-cloudy.svg",
    "Névoa com vento": "src/assets/day_svg/wi-day-fog.svg",
    "Chuveiros com vento":"src/assets/day_svg/wi-day-hail.svg",
    "Trovoadas com vento": "src/assets/day_svg/wi-day-thunderstorm.svg",
    "Chuva com vento": "src/assets/day_svg/wi-day-rain.svg",
    "Flocos de neve com vento": "src/assets/day_svg/wi-day-flurries.svg",
    "Neve com vento": "src/assets/day_svg/wi-day-snow.svg",
    "Gelo com vento": "src/assets/day_svg/wi-day-snow.svg",
    "Granizo com vento": "src/assets/day_svg/wi-day-sprinkle.svg",
    "Chuva congelante com vento": "src/assets/day_svg/wi-day-sleet-storm.svg",
    "Chuva e neve com vento": "src/assets/day_svg/wi-day-sleet-storm.svg"
  },
  night:{
    "Céu claro": "src/assets/night _svg/wi-night-clear.svg",
    "Predominantemente aberto": "src/assets/night _svg/wi-night-clear.svg",
    "Parcialmente nublado": "src/assets/night _svg/wi-night-clear.svg",
    "Nuvens intermitentes": "src/assets/night _svg/wi-night-alt-partly-cloudy.svg",
    "Neblina com céu claro": "src/assets/night _svg/wi-night-cloudy-windy.svg",
    "Predominantemente nublado": "src/assets/night _svg/wi-night-alt-cloudy.svg",
    "Nublado": "src/assets/night _svg/wi-night-alt-cloudy.svg",
    "Encoberto": "src/assets/night _svg/wi-cloudy.svg",
    "Névoa": "src/assets/night _svg/wi-night-fog.svg",
    "Chuveiros": "src/assets/night _svg/wi-night-alt-hail.svg",
    "Predominantemente nublado com chuveiros": "src/assets/night _svg/wi-night-alt-hail.svg",
    "Parcialmente nublado com chuveiros": "src/assets/night _svg/wi-night-alt-hail.svg",
    "Trovoadas": "src/assets/night _svg/wi-night-alt-thunderstorm.svg",
    "Predominantemente nublado com trovoadas": "src/assets/night _svg/wi-night-alt-thunderstorm.svg",
    "Parcialmente nublado com trovoadas": "src/assets/night _svg/wi-night-alt-thunderstorm.svg",
    "Chuva": "src/assets/night _svg/wi-night-alt-rain.svg",
    "Flocos de neve": "src/assets/night _svg/wi-night-alt-flurries.svg",
    "Predominantemente nublado com flocos de neve": "src/assets/night _svg/wi-night-alt-flurries.svg",
    "Parcialmente nublado com flocos de neve": "src/assets/night _svg/wi-night-alt-flurries.svg",
    "Neve": "src/assets/night _svg/wi-night-alt-snow.svg",
    "Predominantemente nublado com neve": "src/assets/night _svg/wi-night-alt-snow.svg",
    "Gelo": "src/assets/night _svg/wi-night-alt-snow.svg",
    "Granizo": "src/assets/night _svg/wi-night-alt-sprinkle.svg",
    "Chuva congelante": "src/assets/night _svg/wi-night-alt-snow-thunderstorm.svg",
    "Chuva e neve": "src/assets/night _svg/wi-night-alt-snow-thunderstorm.svg",
    "Claro com vento": "src/assets/night _svg/wi-night-clear.svg",
    "Predominantemente claro com vento": "src/assets/night _svg/wi-night-clear.svg",
    "Parcialmente nublado com vento": "src/assets/night _svg/wi-night-clear.svg",
    "Predominantemente nublado com vento": "src/assets/night _svg/wi-night-alt-cloudy.svg",
    "Neblina com vento": "src/assets/night _svg/wi-night-fog.svg",
    "Chuveiros com vento": "src/assets/night _svg/wi-night-alt-hail.svg",
    "Trovoadas com vento": "src/assets/night _svg/wi-night-alt-thunderstorm.svg",
    "Chuva com vento": "src/assets/night _svg/wi-night-alt-rain.svg",
    "Flocos de neve com vento": "src/assets/night _svg/wi-night-alt-flurries.svg",
    "Neve com vento": "src/assets/night _svg/wi-night-alt-snow.svg",
    "Gelo com vento": "src/assets/night _svg/wi-night-alt-snow.svg",
    "Granizo com vento": "src/assets/night _svg/wi-night-alt-sprinkle.svg",
    "Chuva congelante com vento": "src/assets/night _svg/wi-night-alt-snow-thunderstorm.svg",
    "Chuva e neve com vento": "src/assets/night _svg/wi-night-alt-snow-thunderstorm.svg"
  },
};

export default weatherIcons;